### ISSUE TITLE
Feature Request - Support audio reference in 1SatOrdinals Wallet

### ISSUE THREAD

**Issue by jdh7190** [BitcoinSchema/1sat-website#7]
If individual inscriptions or artifacts have an on-chain audio reference, for example:

audio: b://txid

Then it would be nice to have the wallet be able to play the audio. This is relevant for sMon Robots:

e17d7856c375640427943395d2341b6ed75f73afc8b22bb3681987278978a584

As well as future inscriptions of audio tracks, albums, etc.

**Comment by rohenaz** [comment]
this was added
